### ISSUE TITLE
Implementing additional attributes for test cases

### ISSUE THREAD

**Issue by eric-chou** [AHRQ-CDS/CQL-Testing-Framework#1] opened 2019-09-26 19:53 UTC
Hello,
I am a researcher at the University of Pittsburgh Department of Biomedical Informatics and our lab [forked](https://github.com/dbmi-pitt/CQL-Testing-Framework) this repository in order to work with it for drug-drug interaction alerting. For many of our use cases, though, we would like to be able to use STU3 MedicationStatement items such as "dosage" and the amount for each [ingredient(s)](https://hl7.org/fhir/STU3/medication-definitions.html#Medication.ingredient) of the medication. We understand that currently "[dosage](https://hl7.org/fhir/STU3/dosage.html#Dosage)" is not a [supported attribute ](https://github.com/AHRQ-CDS/CQL-Testing-Framework/blob/master/CREATING-TEST-CASES.md), but on our fork I have looked into how to implement these ourselves via the src file [loadYamlTestCases.js](https://github.com/AHRQ-CDS/CQL-Testing-Framework/blob/master/src/loadYamlTestCases.js) in the function "handleMedicationStatement". 

I have only gotten this to be able to partially work for implementing dosage, though, basically by adding a line for "dosage: d.dosage ? d.dosage : undefined" in the "handleMedicationStatement" return statement. Below are a couple of screenshots of how the YAML I am trying to test is outputted with this addition. It looks like only the dosage text made it through but none of the other "dosage" elements.

![image](https://user-images.githubusercontent.com/9423731/65720013-0d460980-e075-11e9-892c-f3d0555e2d18.png)

![image](https://user-images.githubusercontent.com/9423731/65720257-93fae680-e075-11e9-9489-65b3a728714b.png)

So overall:
- Is there a general process that you all have for implementing new attributes for these resources?
- Do you have additional pointers for which files/functions I should look into that are necessary to keep up to date for implementing additional attributes?

Thank you!
-Eric

**Comment by cmoesel** [comment] 2019-09-27 02:04
Hi @eric-chou! Thanks for reaching out! The CQL Testing Framework has not been out very long, so it's great to see people like you using it!

We do plan on implementing additional resources and extending current resources, but I realize that does not help you much right *now*.  I think it would be great for us to provide documentation for how others can extend the Test Case framework as well.  That's a great idea!

For the time being, I'm hoping that maybe @dwwinters can help you with your immediate inquiry. He's quite familiar with the framework and can probably point you in the right direction!

**Comment by dwwinters** [comment] 2019-09-27 14:20
Hi @eric-chou.  I set up a test case on my end following your description of the change you made to `handleMedicationStatement`, but was not able to reproduce the behavior shown in your second screenshot (I don't get `undefined` for any of the `dosage` elements).  Have you tried enabling dump files in the [cqlt.yaml file](https://github.com/AHRQ-CDS/CQL-Testing-Framework/blob/master/README.md#the-cqltyaml-file)?  In my local test case I added this to my `cqlt.yaml` file:

```yaml
options:
  dumpFiles:
    enabled: true
```

This will cause the test framework to output each test case as a JSON-formatted FHIR bundle.  When I do this I get the following included in my `MedicationStatement` resource:

```json
"dosage": [
  {
    "text": "once daily",
    "timing": [
      {
        "repeat": [
          {
            "frequency": 1,
            "period": 1,
            "periodUnit": "d"
          }
        ],
        "doseQuantity": [
          {
            "value": 1,
            "unit": "tablet"
          }
        ]
      }
    ]
  }
],
```

**Comment by eric-chou** [comment] 2019-09-27 16:49
Thank you both for the reply! @dwwinters previously I wasn't aware of dump files but now I did find the json bundles outputted under the dump_files directory and mine does reflect that. I should have specified though that the "undefined" elements in dosage come from the CQL rather than the dump files. In the CQL I am running on the test case I am currently using it to just output the full medication statement simply so I can see what the CQL is using, and it is through this that I am getting the output that I screenshotted.

Below is the CQL that yields my output:

```
define "Report Citaloprams":
  "Citaloprams" S
  return {
    Type:  'Statement',
    Name:  ConceptText(S.medication as FHIR.CodeableConcept),
    Start: MedicationStatementDate(S),
    End:   DateTimeText((S.effective as FHIR.Period)."end"),
    Statement: S,
    Dosage: S.dosage,
    Status: S.status.value
  }
  sort by Start desc, End desc
```

This is the "summary" method" where that is called and is used for the test:

```
define Summary: {
  Patient: {
    Name: Combine(Patient.name.given G return G.value, ' ') + ' ' + Combine(Patient.name.family F return F.value, ' '),
    Gender: Patient.gender.value,
    Age: AgeInYears()
  },
  HistoricalTreatments: {
    CitalopramMedications: "Report Citaloprams",
    QTProlongingAgents: "Report QT Prolonging Agents"
  }
}
```

And I'm attaching a text file of the command line output from this.
[test.txt](https://github.com/AHRQ-CDS/CQL-Testing-Framework/files/3663791/test.txt)

So overall, it looks to me like it IS able to read the dosage as expected but for some reason this is readable to be seen in the dump file, but not in the CQL. Does that sound right?

Thanks!

**Comment by dwwinters** [comment] 2019-09-30 12:31
Thanks for the additional information @eric-chou.  So getting back to one of your original questions: Yes, the approach you took to adding dosage would generally be what we would do for implementing additional attributes.  But care must be taken to ensure what gets generated by the testing framework is formatted properly per the FHIR spec.  The line you added just takes the dosage element directly from the YAML without any sort of checks other than making sure it is not `undefined`.  To eliminate the possibility that the added dosage element is messing up the execution of your CQL, I would try running against a test case without any dosage information.  If you're still getting `undefined` elements coming out of your CQL, then I would try again with a `MedicationStatement` resource that you know is 100% valid.  If you're still getting issues after that, I would take a look at your CQL; perhaps there is an issue there?  I would try just querying for the `MedicationStatement` and examining the resulting expression in the dumped output.

**Comment by cmoesel** [comment] 2019-09-30 13:00
Hi @eric-chou.  Upon further inspection, @dwwinters is right on.  Looking at your initial report, you have the following YAML:

```yaml
-
  resourceType: MedicationStatement
  code: RXNORM#283672 Citalopram 10 MG Oral Tablet
  effectiveDateTime: 2019-07-30T00:00:00.000+00:00
  dosage:
  -
    text: once daily
    timing:
    -
      repeat:
      -
        frequency: 1
        period: 1
        periodUnit: d
    doseQuantity:
    -
      value: 1
      unit: tablet
```

Because you put the `-` after `timing:`, that makes `timing` an array; but if you look at the FHIR STU3 definition of [Dosage](http://hl7.org/fhir/STU3/dosage.html#Dosage), `timing` is `0..1`, so it should not be an array in the YAML.  Similarly, within the `timing`, `repeat` should also not be an array (it is `0..1`).  And the same goes for `doseQuantity`.

So in order to make YAML that fits the format of FHIR STU3 Dosage, I think your YAML needs to be more like this:

```yaml
-
  resourceType: MedicationStatement
  code: RXNORM#283672 Citalopram 10 MG Oral Tablet
  effectiveDateTime: 2019-07-30T00:00:00.000+00:00
  dosage:
  -
    text: once daily
    timing:
      repeat:
        frequency: 1
        period: 1
        periodUnit: d
    doseQuantity:
      value: 1
      unit: tablet
```

**Comment by eric-chou** [comment] 2019-09-30 18:29
That fix worked for me, thank you both very much for your help! It looks like next I'll try to use these attributes in CQL now and see how that works out.

**Comment by cmoesel** [comment] 2019-09-30 18:43
You're welcome.  I'm glad it worked out!  I'm going to close this issue, but if you encounter any other problems, feel free to open a new issue.

**Closed as completed by cmoesel** 2019-09-30 18:43 UTC
